version: "3.9"
name: "investment-diary"
services:
  db_prod:
    image: mysql:latest
    container_name: ${DB_HOST}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - db_conn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 5
  investment_app:
    image: investment-app:${APP_VERSION}
    container_name: ${APP_LOCATION}
    ports:
      - "8080:8080"
    networks:
      - db_conn
      - app_conn
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_URL=jdbc:${DB_VENDOR}://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DB_DIALECT=${DB_DIALECT}
      - DB_DDL=${DB_DDL}
      - API_VERSION=${API_VERSION}
    depends_on:
      db_prod:
        condition: service_healthy
networks:
  db_conn:
    internal: true
    name: "db_conn"
  app_conn:
    driver: bridge
